"""recipe ingredient images, nullable quantity

Revision ID: 5bae32b93b0a
Revises: 6cf630de4d7b
Create Date: 2026-09-08 00:53:34.051230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bae32b93b0a'
down_revision: Union[str, Sequence[str], None] = '6cf630de4d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('user_ingredients', 'quantity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_ingredients', 'quantity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('recipe_ingredient_images')
    # ### end Alembic commands ###
