"""add password_reset_otps table

Revision ID: 62fe171a48b4
Revises: 11e6973ba456
Create Date: 2026-09-12 19:28:51.407118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fe171a48b4'
down_revision: Union[str, Sequence[str], None] = '11e6973ba456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_hash', sa.String(length=64), nullable=True),
    sa.Column('ticket_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_hash')
    )
    op.create_index('ix_password_reset_otps_active_lookup', 'password_reset_otps', ['user_id', 'consumed_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_user_id'), 'password_reset_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_otps_user_id'), table_name='password_reset_otps')
    op.drop_index('ix_password_reset_otps_active_lookup', table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
