"""add nutrition engine schema

Hand-written (not autogenerated): `alembic revision --autogenerate` needs a
live database connection, and no Postgres was reachable while the Nutrition
Engine branch was developed. Written to match backend/database/models.py's
IngredientNutrition, IngredientNutritionAlias and BaseRecipe classes exactly.
NOT yet applied against a real database -- run `alembic upgrade head` against
a real Postgres and diff with `alembic check` before trusting it.

Revision ID: a1b2c3d4e5f6
Revises: 62fe171a48b4
Create Date: 2026-09-26 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '62fe171a48b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('ingredient_nutrition', sa.Column('source_ref', sa.String(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('portion_grams', sa.JSON(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('derivation', sa.JSON(), nullable=True))

    op.create_table('ingredient_nutrition_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('ingredient_nutrition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_nutrition_id'], ['ingredient_nutrition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_ingredient_nutrition_aliases_alias')
    )
    op.create_index(op.f('ix_ingredient_nutrition_aliases_alias'), 'ingredient_nutrition_aliases', ['alias'], unique=False)

    op.add_column('base_recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('base_recipes', sa.Column('ingredient_quantities', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('base_recipes', 'ingredient_quantities')
    op.drop_column('base_recipes', 'servings')

    op.drop_index(op.f('ix_ingredient_nutrition_aliases_alias'), table_name='ingredient_nutrition_aliases')
    op.drop_table('ingredient_nutrition_aliases')

    op.drop_column('ingredient_nutrition', 'derivation')
    op.drop_column('ingredient_nutrition', 'portion_grams')
    op.drop_column('ingredient_nutrition', 'source_ref')
